
development:
  adapter: postgresql
  host: localhost
  username: postgres
  database: outage_informer_dev

test:
  adapter: postgresql
  host: localhost
  username: postgres
  database: outage_informer_test

production:
  adapter: postgresql
  host: localhost
  username: postgres
  database: outage_informer_prod